services:
  minio:
    image: quay.io/minio/minio
    # This is EXTREMELY WEAK security. Don't use in production
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  minio_data:
    driver: local
